### ISSUE TITLE
Add TLB

### ISSUE THREAD

**Issue by chaoRIOS** [chaoRIOS/riscv-rust#3]
expose interface at [mmu.rs](https://github.com/chaoRIOS/riscv-rust/blob/3f45308e32e517d5b8050a3f30d104b3ba14f452/src/mmu.rs#L674)

**Comment by chaoRIOS** [comment]
version: [707b4ac](https://github.com/chaoRIOS/riscv-rust/commit/707b4ac1d168a31747d3c1a83523a62eff4fe8d0)



1. In `setup_program`
```rust
while memdump_contents[iter_num] != 'x' as u8 {
    iter_num = iter_num + 1;
}
```

```bash
thread 'main' panicked at 'index out of bounds: the len is 82 but the index is 82', src/lib.rs:231:23
```


2. If I comment out `memory dump` section, then get
```bash
Warn: Changing SATP to 9223372036855300118
detecter VADDR=2147483648
AddressingMode=SV39 user
ERROR: at translate_address paddr==err(())
Warn: changing PRIVILEGE MODE to machine
detecter VADDR=0
AddressingMode=SV39 Machine Execute
detecter PADDR=0
thread 'main' panicked at 'index out of bounds: the len is 268435456 but the index is 2305843008945258496', src/memory.rs:35:10
```
